export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  huge: 40,

  borderRadius: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 22,
    xl: 28,
    full: 9999,
  },

  // Neumorphic Soft Dual Shadows for Light/White Surfaces
  neu: {
    raised: {
      shadowColor: '#94A3B8',
      shadowOffset: { width: 4, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 5,
      borderTopWidth: 1.5,
      borderLeftWidth: 1.5,
      borderTopColor: '#FFFFFF',
      borderLeftColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderRightWidth: 1,
      borderBottomColor: 'rgba(148, 163, 184, 0.35)',
      borderRightColor: 'rgba(148, 163, 184, 0.35)',
    },
    raisedSm: {
      shadowColor: '#94A3B8',
      shadowOffset: { width: 3, height: 4 },
      shadowOpacity: 0.28,
      shadowRadius: 5,
      elevation: 3,
      borderTopWidth: 1.5,
      borderLeftWidth: 1.5,
      borderTopColor: '#FFFFFF',
      borderLeftColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderRightWidth: 1,
      borderBottomColor: 'rgba(148, 163, 184, 0.25)',
      borderRightColor: 'rgba(148, 163, 184, 0.25)',
    },
    recessed: {
      borderTopWidth: 1.5,
      borderLeftWidth: 1.5,
      borderTopColor: 'rgba(148, 163, 184, 0.45)',
      borderLeftColor: 'rgba(148, 163, 184, 0.45)',
      borderBottomWidth: 1.5,
      borderRightWidth: 1.5,
      borderBottomColor: '#FFFFFF',
      borderRightColor: '#FFFFFF',
    },
    glow: (color: string) => ({
      shadowColor: color,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 6,
    }),
  },

  shadows: {
    sm: {
      shadowColor: '#94A3B8',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
    },
    md: {
      shadowColor: '#94A3B8',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 4,
    },
    lg: {
      shadowColor: '#94A3B8',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    },
    glow: (color: string) => ({
      shadowColor: color,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 6,
    }),
  },
};
